### ISSUE TITLE
.npmignore file

### ISSUE THREAD

**Issue by ORESoftware** [rvagg/node-du#3]
quite ironically I was using du at the command line to see which modules were taking up space on my filesystem, looking in node_modules, I see:

```
28      ./du/node_modules/async/lib
88      ./du/node_modules/async
92      ./du/node_modules
128     ./du
```

forgive me if I mistaken, but when publishing to NPM looks like node_modules from this project is being included. the idea would be to add an .npmignore file in this project and add "node_modules" to that file and then publish to NPM

let me know if maybe I wrong about something thanks!

**Comment by rvagg** [comment]
it's ignored in `.gitignore` which is respected by npm when publishing, when you do `npm install du` it installs node_modules/async for you because I've specified it in the `"dependencies"` field of `package.json`.
